In [1]:
import numpy as np

In [3]:
print(f"{np.__version__}")

1.24.3


# **Example 1 : Calculating Total Revenue**

In [4]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [5]:
quantiles = np.array([10, 5, 8, 12, 3])
quantiles

array([10,  5,  8, 12,  3])

In [6]:
revenue_per_product = prices * quantiles
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [8]:
total_revenue = np.sum(revenue_per_product)
total_revenue

664.62

# **Example 2: Analyzing Blog Post Stats**

In [9]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [11]:
max_views = np.max(views)
max_views

1200

In [12]:
min_views = np.min(views)
min_views

300

In [14]:
average_views = np.round(np.mean(views), 2)
average_views

733.33

In [15]:
total_views = np.sum(views)
total_views

4400

# **Example 3 : Splitting Order into Batches**

In [23]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [24]:
batches = np.split(order_ids, 2)
batches

[array([1001, 1002, 1003, 1004]), array([1005, 1006, 1007, 1008])]

In [25]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [26]:
for batch in batches:
    print(batch)

[1001 1002]
[1003 1004]
[1005 1006]
[1007 1008]


# **Example 4 : Categorizing Product Rating**

In [27]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [28]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [29]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

# **Example 5 : Calculate Total And Average quantiles sold**

In [30]:
# Each column is specific
# Each row represents specific order

order_quantiles = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantiles

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [31]:
total_quantiles_sold = np.sum(order_quantiles)
total_quantiles_sold

45

In [32]:
# Quantiles of the sales of each product
total_quantiles_per_product = np.sum(order_quantiles, axis = 0)
total_quantiles_per_product

array([15,  9,  5, 16])

In [33]:
# Quantiles of the sales in each order
total_quantiles_per_order = np.sum(order_quantiles, axis = 1)
total_quantiles_per_order

array([17, 28])

In [34]:
# Average quantiles per product
average_quantiles_per_product = np.mean(order_quantiles, axis = 0)
average_quantiles_per_product 

array([7.5, 4.5, 2.5, 8. ])

# **Example 6 : Calculate Average product Rating and Maximum rating per Category**

In [35]:
# Each row represents specific product
# Each product is rated in 4 different categories

product_reviews = np.array([[4.5, 3.2, 2.5, 5.0], [4.3, 3.8, 1.0, 4.8], [2.0, 3.6, 4.7, 0.5]])
product_reviews

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [36]:
average_rating = np.mean(product_reviews, axis = 1)
average_rating

array([3.8  , 3.475, 2.7  ])

In [37]:
max_rating_per_category = np.max(product_reviews, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

# **Example 7 : Generation of the sample stock data**

In [49]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Monday, 1 Apr', 'Tuesday, 2 Apr']
price_types = ['Open', 'Close', 'High', 'Low']

In [50]:
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [52]:
stock_prices.shape

(3, 2, 4)

In [53]:
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}:")
    for index_axis_1, day in enumerate(days):
        print(f"Day : {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}")
        print('')
    print('')
    

Stock prices for the Google:
Day : Monday, 1 Apr
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day : Tuesday, 2 Apr
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day : Monday, 1 Apr
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day : Tuesday, 2 Apr
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day : Monday, 1 Apr
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day : Tuesday, 2 Apr
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


