# **Filling a Numpy Array With Zeros, Ones, Or Random Floats**

In [ ]:
import numpy as np

In [4]:
print(f"{np.__version__}")

1.24.3


In [5]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones((2, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.random.random((3, 4))

array([[0.35445364, 0.05667851, 0.42949309, 0.09579719],
       [0.03598332, 0.90764105, 0.36256529, 0.41419316],
       [0.71539985, 0.82026475, 0.16252585, 0.959563  ]])

# **Generating Random Elements Using randint and uniform**

In [9]:
np.random.randint(10, 20, size=(4, 5))

array([[12, 17, 12, 17, 15],
       [10, 10, 17, 19, 17],
       [18, 10, 18, 15, 11],
       [11, 13, 12, 16, 11]])

In [12]:
np.random.uniform(10.0, 50.0, size=(4, 5))

array([[32.95838605, 37.35125077, 32.72048282, 13.91733125, 28.93492781],
       [49.08539659, 37.83516135, 18.51463972, 10.15593798, 48.58636209],
       [19.97755622, 44.32504566, 28.88557438, 12.15302933, 33.71383961],
       [30.46487074, 15.68051108, 18.10946675, 28.09559215, 21.59453998]])

# **Understaning Seed Number**

In [18]:
np.random.seed(10)
np.random.random((3, 4, 10, 5))

array([[[[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
         [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
         [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
         [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
         [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317],
         [0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895],
         [0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935],
         [0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715],
         [0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264],
         [0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ]],

        [[0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445],
         [0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413],
         [0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177],
         [0.35718176, 0.07961309, 0.30545992, 0.33071931, 0.7738303 ],
    

In [16]:
np.random.seed(1)
np.random.randint(10, 20, size=(4, 5))

array([[15, 18, 19, 15, 10],
       [10, 11, 17, 16, 19],
       [12, 14, 15, 12, 14],
       [12, 14, 17, 17, 19]])

In [17]:
# Seed value is generated automatically
np.random.uniform(10.0, 50.0, size=(4, 5))

array([[27.22794269, 47.56511158, 41.13556945, 38.63882064, 42.11030016],
       [13.71203235, 30.72610196, 44.60081008, 43.16587629, 43.18413438],
       [20.92199897, 12.36972805, 36.8211216 , 33.72262073, 36.8661639 ],
       [26.47151516, 17.90203592, 21.58518562, 15.68480542, 41.33257891]])