In [1]:
import numpy as np

In [3]:
print(f"{np.__version__}")
      

1.24.3


In [4]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [5]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [8]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [9]:
np.array([10, 2, 5, 7, 9, 15, 25, 30, 35, 40]).reshape([2, 5])

array([[10,  2,  5,  7,  9],
       [15, 25, 30, 35, 40]])

In [11]:
np.array([10, 2, 5, 7, 9, 15, 25, 30, 35, 40]).reshape([2, 5]).reshape([10, 1])

array([[10],
       [ 2],
       [ 5],
       [ 7],
       [ 9],
       [15],
       [25],
       [30],
       [35],
       [40]])

In [12]:
np.random.random((4, 3, 3))

array([[[9.38848030e-01, 1.71922600e-01, 4.94944787e-01],
        [6.49925871e-01, 5.09469789e-01, 2.92666097e-02],
        [2.59019400e-02, 6.88636998e-06, 8.85774160e-01]],

       [[1.50070411e-02, 8.85003816e-01, 1.13171612e-01],
        [2.12422797e-01, 1.86003865e-01, 9.47368195e-01],
        [2.08330123e-01, 4.52549464e-01, 6.23901878e-01]],

       [[8.33832301e-03, 1.76976455e-01, 1.52037417e-01],
        [2.86670493e-01, 2.39144978e-01, 5.66232666e-02],
        [7.17034871e-01, 3.81126252e-01, 4.97008274e-01]],

       [[6.85013521e-01, 2.95085144e-01, 4.58713657e-01],
        [3.88556256e-01, 2.02877166e-01, 1.60017185e-01],
        [5.38529927e-01, 7.45546050e-01, 6.23326719e-01]]])

In [13]:
np.random.random((4, 3, 3)).flatten()

array([0.63945705, 0.6850007 , 0.19946971, 0.67279952, 0.50872372,
       0.18492283, 0.31232868, 0.03158207, 0.4946423 , 0.74317211,
       0.48532056, 0.12868548, 0.83681179, 0.80844259, 0.0709103 ,
       0.78065568, 0.02062113, 0.62139038, 0.06985723, 0.58695835,
       0.70198389, 0.03782114, 0.94361762, 0.26042036, 0.99316921,
       0.46937445, 0.26440738, 0.80799486, 0.5928013 , 0.55850639,
       0.67884852, 0.45038716, 0.37557263, 0.34921872, 0.99742122,
       0.99718488])

In [14]:
np.random.random((4, 3, 3)).flatten().shape

(36,)