In [1]:
import numpy as np

In [2]:
print(f"{np.__version__}")

1.24.3


In [3]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
first.shape

(2, 3)

In [5]:
first[0, 0]

1

In [7]:
first[0][0]

1

In [6]:
first[1, 2]

6

# **Arithmetic Operations With Numpy Arrays**

In [19]:
first = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
second = np.array([[7, 8, 9], [10, 11, 12]])

In [21]:
first.shape

(2, 3)

In [22]:
second.shape

(2, 3)

In [11]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [12]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
first - 2 

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [14]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [23]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.concatenate((first, second), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [25]:
# Concatenate two single dimensional arrays
np.concatenate((np.array([1, 2, 3]), np.array([4, 5, 6])))

array([1, 2, 3, 4, 5, 6])